# -*- coding: utf-8 -*-
URLs = ['https://www.sec.gov/Archives/edgar/data/895421/000090514813000498/efc13-310_fmfwp.htm',
'https://www.sec.gov/Archives/edgar/data/831001/000119312515143451/d915066dfwp.htm',
'https://www.sec.gov/Archives/edgar/data/1281761/000119312513174674/d524796dfwp.htm',
'https://www.sec.gov/Archives/edgar/data/40729/000119312511053849/dfwp.htm'
]
            
configSet = {
                'Par Amount':'principalRow',
                'Re-offer Spread to Benchmark':'spreadToBenchmarkRow',
                'Ratings (Moodys/S&P/Fitch)*':'ratingRow',
                'Redemption at Issuer’s Option':'redemptionRow',
                'Optional Redemption':'redemptionRow',
                'ISSUE PRICE':'priceRow',
                'Senior Co-Managers':'managerRow',
                'PRICING BENCHMARK':'pricingBenchmarkRow',
                'Minimum Denomination / Multiples':'denominationRow',
                'Net Proceeds to Issuer':'proceedsIssuerRow',
                'issuer':'issuerRow',
                'CUSIP/ISIN Numbers':'cusipIsinRow',
                'CUSIP / ISIN':'cusipIsinRow',
                'CUSIP':'cusipRow',
                'Guarantee':'guaranteeRow',
                'Original Issue Date (Settlement)':'settlementRow',
                'Price to Public':'priceRow',
                'Optional Redemption':'redemptionAtIssuerOptionRow',
                'MATURITY DATE':'maturityRow',
                'Sole Book Manager':'bookRunnerRow',
                'INTEREST PAYMENT DATES':'interestPaymentRow',
                'Redemption at Issuer Option':'redemptionAtIssuerOptionRow',
                'Benchmark Treasury Spot and Yield':'benchmarkYieldRow',
                'Redemption for Tax Purposes':'otherRedemptionRow',
                'Minimum Denomination':'denominationRow',
                'Sinking Fund':'sinkingFundRow',
                'Final Maturity Date':'maturityRow',
                'Gross Proceeds to Selling Securityholder':'proceedsIssuerRow',
                'Coupon and Interest Payment Dates':'interestPaymentRow',
                'Defeasance':'defeasanceRow',
                'TRADE DATE':'tradeRow',
                'SPREAD TO BENCHMARK':'spreadToBenchmarkRow',
                'Day Count':'dayCountConventionRow',
                'PRINCIPAL AMOUNT':'principalRow',
                'RATING':'ratingRow',
                'PROCEEDS TO ISSUER':'proceedsIssuerRow',
                'Public Offering Price':'priceRow',
                'COUPON':'couponRow',
                'Net Proceeds to Citigroup':'proceedsIssuerRow',
                'ISIN':'isinRow',
                'Special Event Redemption':'otherRedemptionRow',
                'EXPECTED RATINGS*':'ratingRow',
                'CO-MANAGERS':'managerRow',
                'BOOKRUNNERS':'bookRunnerRow',
                'Interest Rate':'couponRow',
                'DENOMINATIONS':'denominationRow',
                'DAY COUNT CONVENTION':'dayCountConventionRow',
                'LISTING':'listingRow',
                'Benchmark Treasury':'pricingBenchmarkRow',
                'Aggregate Principal Amount':'principalRow',
                'Settlement Date':'settlementRow',
                'Ratings*':'ratingRow',
                'RE-OFFER YIELD':'yieldRow',
                'REDEMPTION TERMS':'redemptionAtIssuerOptionRow',
                'Joint Book-Running Managers':'bookRunnerRow',
                'Issuer Ratings':'ratingRow',
                'Issue Price (Price to Public)':'priceRow',
                'BENCHMARK YIELD':'benchmarkYieldRow',
                'Interest Determination Date':'interestDeterminationRow',
                'MATURITY':'maturityRow',
                'CUSIP/ISIN':'cusipIsinRow',
                'Semi-Annual Coupon':'couponRow',
                'Junior Co-Managers':'managerRow',
                'Joint Bookrunners':'bookRunnerRow',
                'Redemption at Issuers Option':'redemptionAtIssuerOptionRow',
                'Net Proceeds to Issuer (after underwriting discounts and commissions and before offering expenses)':'proceedsIssuerRow',
                'Yield to Maturity':'yieldRow',
                'Spread to Benchmark Treasury':'spreadToBenchmarkRow',
                'COUPON FREQUENCY':'couponFrequencyRow',
                'Expected Issue Ratings':'ratingRow',
                'REDEMPTION COMMENCEMENT DATE':'redemptionRow',
                }

URLsData = {'https://www.sec.gov/Archives/edgar/data/895421/000090514813000498/efc13-310_fmfwp.htm':'1',
            'https://www.sec.gov/Archives/edgar/data/831001/000119312515143451/d915066dfwp.htm':'1',
            'https://www.sec.gov/Archives/edgar/data/1281761/000119312513174674/d524796dfwp.htm':'1',
            'https://www.sec.gov/Archives/edgar/data/40729/000119312511053849/dfwp.htm':'1',
            'https://www.sec.gov/Archives/edgar/data/1390777/000119312516745446/d211567dfwp.htm':'2',
            'https://www.sec.gov/Archives/edgar/data/93751/000119312516592072/d136154dfwp.htm':'1'}
