# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_persistence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='eventKeywords',
        ),
        migrations.AlterField(
            model_name='categories',
            name='categoryName',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='entity',
            name='category',
        ),
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.ManyToManyField(to='data_persistence.Categories'),
        ),
        migrations.DeleteModel(
            name='EventKeywords',
        ),
    ]
