# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_persistence', '0002_auto_20170105_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='data_persistence.Categories'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='data_persistence.Keywords'),
        ),
    ]
