# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_persistence', '0003_auto_20170105_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='contentItemURL',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
