# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_persistence', '0004_auto_20170105_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='contentItemPublishDate',
            field=models.DateField(null=True),
        ),
    ]
