# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_persistence', '0006_auto_20170105_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='contentTitle',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
