# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_persistence', '0007_contentitem_contenttitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='contentSummary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentsource',
            name='contentItemType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_persistence.ContentItemType'),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='contentItemPublishDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='contentItemReceiveDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfavorites',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwatchlist',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwatchlistdetails',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
