# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_persistence', '0009_auto_20170125_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='contentItemPublishDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='contentItemReceiveDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
